"""Rule 1, enforced: the docs must quote Data/metrics.json, never a typed number.

`--verify-metrics` already answers "does metrics.json still describe this
code?". It never answered "do the documents still quote metrics.json?", and
that gap shipped a wrong headline twice:

  * v5.0 - whitepaper said 90.00% / macro F1 0.8791, the code produced
    87.50% / 0.8498.
  * 2026-09-17 - docs/ACTION_PLAN.md headlined episode sensitivity 87.5% and
    6.0 alarms/hour. README.md had retracted that exact pair on 2026-08-19 as
    belonging to a RandomForest that was already replaced; the shipped model
    measures 100.0% and 7.8/hour. The plan under-reported its own result.

Any `<!-- metrics:KEY -->` region in a markdown file is generated by
scripts/sync_metrics_blocks.py from Data/metrics.json. This test fails the
moment one of them drifts, so a stale figure cannot reach a reviewer.

    python scripts/sync_metrics_blocks.py        # regenerate every block
"""
import os
import subprocess
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SYNC = os.path.join(REPO_ROOT, "scripts", "sync_metrics_blocks.py")


def test_doc_metrics_blocks_match_metrics_json():
    assert os.path.isfile(SYNC), f"missing {SYNC}"
    proc = subprocess.run(
        [sys.executable, SYNC, "--check"],
        capture_output=True, text=True, cwd=REPO_ROOT,
    )
    detail = (proc.stdout or "") + (proc.stderr or "")
    assert proc.returncode == 0, (
        "a documented figure no longer matches Data/metrics.json.\n"
        "Regenerate with:  python scripts/sync_metrics_blocks.py\n\n" + detail
    )
